"""Central constants for the populate_janno package."""
import numpy as np

VERSION = "0.1.1"
AUTORUN_EAGER_ROOT = "/mnt/archgen/Autorun_eager"

CONTAMINATION_SNP_CUTOFF_DEFAULT = 100
GENOTYPE_PLOIDY_DEFAULT = "haploid"

BAM_SEARCH_DIRS = [
    "merged_bams/initial",
    "trimmed_bam",
    "merged_bams/additional",
    "deduplication",
]

MT_CAPABLE_ANALYSES = ["RM", "TM"]

JANNO_DTYPES = {
    "Poseidon_ID" : "str",
    "Genetic_Sex" : "str",
    "Group_Name" : "str",
    "Individual_ID" : "str",
    "Species" : "str",
    "Alternative_IDs" : "str",
    "Alternative_IDs_Context" : "str",
    "Relation_To" : "str",
    "Relation_Degree" : "str",
    "Relation_Type" : "str",
    "Collection_ID" : "str",
    "Custodian_Institution" : "str",
    "Cultural_Era" : "str",
    "Cultural_Era_URL" : "str",
    "Archaeological_Culture" : "str",
    "Archaeological_Culture_URL" : "str",
    "Country" : "str",
    "Country_ISO" : "str",
    "Location" : "str",
    "Site" : "str",
    "Latitude" : np.float32,
    "Longitude" : np.float32,
    "Date_Type" : "str",
    "Date_C14_Labnr" : "str",
    "Date_C14_Uncal_BP" : "Int64",
    "Date_C14_Uncal_BP_Err" : "Int64",
    "Date_BC_AD_Start" : "Int64",
    "Date_BC_AD_Median" : "Int64",
    "Date_BC_AD_Stop" : "Int64",
    "Chromosomal_Anomalies" : "str",
    "MT_Haplogroup" : "str",
    "Y_Haplogroup" : "str",
    "Source_Material" : "str",
    "Nr_Libraries" : "Int64",
    "Library_Names" : "str",
    "Capture_Type" : "str",
    "UDG" : "str",
    "Library_Built" : "str",
    "Genotype_Ploidy" : "str",
    "Data_Preparation_Pipeline_URL" : "str",
    "Endogenous" : np.float32,
    "Nr_SNPs" : "Int64",
    "Coverage_on_Target_SNPs" : np.float32,
    "Damage" : np.float32,
    "Contamination" : "str",
    "Contamination_Err" : "str",
    "Contamination_Meas" : "str",
    "Genetic_Source_Accession_IDs" : "str",
    "Primary_Contact" : "str",
    "Publication" : "str",
    "Note" : "str",
    "Keywords" : "str",
    "Publication_Status": "str", 
}

JANNO_OUTPUT_COLUMNS = [
    'Poseidon_ID',
    'Genetic_Sex',
    'Group_Name',
    'Individual_ID',
    'Species',
    'Alternative_IDs',
    'Alternative_IDs_Context',
    'Relation_To',
    'Relation_Degree',
    'Relation_Type',
    'Relation_Note',
    'Collection_ID',
    'Custodian_Institution',
    'Cultural_Era',
    'Cultural_Era_URL',
    'Archaeological_Culture',
    'Archaeological_Culture_URL',
    'Country',
    'Country_ISO',
    'Location',
    'Site',
    'Latitude',
    'Longitude',
    'Date_Type',
    'Date_C14_Labnr',
    'Date_C14_Uncal_BP',
    'Date_C14_Uncal_BP_Err',
    'Date_C14_Reservoir_Offset',
    'Date_BC_AD_Start',
    'Date_BC_AD_Median',
    'Date_BC_AD_Stop',
    'Date_Note',
    'Chromosomal_Anomalies',
    'Chromosomal_Anomalies_Note',
    'MT_Haplogroup',
    'Y_Haplogroup',
    'Source_Material',
    'Nr_Libraries',
    'Library_Names',
    'Included_Seq_IDs',
    'Capture_Type',
    'UDG',
    'Library_Built',
    'Genotype_Ploidy',
    'Data_Preparation_Pipeline_URL',
    'Endogenous',
    'Nr_SNPs',
    'Genotyping_BAM',
    'Coverage_on_Target_SNPs',
    'Damage',
    'Contamination',
    'Contamination_Err',
    'Contamination_Meas',
    'Contamination_Note',
    'Genetic_Source_Accession_IDs',
    'Primary_Contact',
    'Publication',
    'Publication_Status',
    'Note',
    'Keywords',
    'Pandora_Tags',
    'Pandora_Projects',
    'RateX',
    'RateY',
    'RateErrX',
    'RateErrY',
]